spring.application.name=inventario

spring.datasource.url=jdbc:postgresql://db.luvkzzwmigbchgdzqfva.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Juanpablofelipenicolasmatias33.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=inventory
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
